//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoalAct1
    {
        public int Id { get; set; }
        public int ActId { get; set; }
        public Nullable<int> GoalId { get; set; }
        public string Name { get; set; }
        public string Color { get; set; }
        public Nullable<int> Imp { get; set; }
        public Nullable<int> Done { get; set; }
    }
}
