//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MainDbEntities : DbContext
    {
        public MainDbEntities()
            : base("name=MainDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Act> Acts { get; set; }
        public virtual DbSet<Sphere> Spheres { get; set; }
        public virtual DbSet<Goal> Goals { get; set; }
        public virtual DbSet<GoalAct1> GoalAct1 { get; set; }
    }
}
