//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sphere
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Color { get; set; }
        public string UserId { get; set; }
        public Nullable<int> CountAct { get; set; }
        public Nullable<int> Archiv { get; set; }
        public string Description { get; set; }
    }
}
